name: react-native-android-build-apk

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']   
      
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
      - name: Prebuild
        run: |
          npx expo prebuild
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

# Generate sonar-project.properties dynamically        
      - name: Generate sonar-project.properties
        run: |
          echo "sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > sonar-project.properties
          echo "sonar.organization=${{ secrets.SONAR_ORGANIZATION }}" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
          echo "sonar.exclusions=**/src/tests/**/*" >> sonar-project.properties
          echo "sonar.coverage.exclusions=**/src/tests/**/*" >> sonar-project.properties
          echo "sonar.tests=./src/tests" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          # echo "sonar.javascript.lcov.reportPaths=./src/tests/coverage/lcov.info" >> sonar-project.properties
          # echo "sonar.testExecutionReportPaths=./test-report.xml" >> sonar-project.propertiesecho "sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > sonar-project.properties
          

      # Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      # Delete sonar-project.properties after  scan
      - name: Remove sonar-project.properties
        if: always()
        run: rm sonar-project.properties
